import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Cuenta } from '../cuenta/entities/cuenta.entity';
import { DetallePedido } from '../detalle-pedido/entities/detalle-pedido.entity';
import { Pedido } from '../pedido/entities/pedido.entity';

@Injectable()
export class ReporteService {
    constructor(
        @InjectRepository(Cuenta)
        private readonly cuentaRepository: Repository<Cuenta>,
        @InjectRepository(DetallePedido)
        private readonly detallePedidoRepository: Repository<DetallePedido>,
        @InjectRepository(Pedido)
        private readonly pedidoRepository: Repository<Pedido>,
    ) { }

    async getVentasGenerales() {
        // Usamos QueryBuilder para agrupar por fecha
        // Convertimos la fecha a string para la agrupación
        const result = await this.cuentaRepository
            .createQueryBuilder('cuenta')
            .select("TO_CHAR(cuenta.updated_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/La_Paz', 'YYYY-MM-DD')", 'fecha')
            .addSelect('SUM(cuenta.total)', 'total_ventas')
            .where('cuenta.D_E_L_E_T_E_D = false')
            .andWhere('cuenta.id_estado = 3') // SOLO CUENTAS PAGADAS
            .groupBy("TO_CHAR(cuenta.updated_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/La_Paz', 'YYYY-MM-DD')")
            .orderBy('fecha', 'ASC')
            .getRawMany();

        return result.map((item) => ({
            fecha: item.fecha,
            total_ventas: parseFloat(item.total_ventas) || 0,
        }));
    }

    async getVentasProducto() {
        const result = await this.detallePedidoRepository
            .createQueryBuilder('dp')
            .innerJoin('dp.producto', 'producto')
            .select('producto.nombre', 'producto')
            .addSelect('SUM(dp.cantidad)', 'cantidad_vendida')
            .addSelect('SUM(dp.subtotal)', 'ingreso_generado')
            .where('dp.D_E_L_E_T_E_D = false')
            .groupBy('producto.id')
            .addGroupBy('producto.nombre')
            .orderBy('cantidad_vendida', 'DESC')
            .getRawMany();

        return result.map((item) => ({
            producto: item.producto,
            cantidad_vendida: parseInt(item.cantidad_vendida, 10),
            ingreso_generado: parseFloat(item.ingreso_generado) || 0,
        }));
    }

    async getRendimientoPersonal(startDate?: string, endDate?: string) {
        let query = this.pedidoRepository
            .createQueryBuilder('pedido')
            .innerJoin('pedido.usuario', 'usuario')
            .innerJoin('usuario.persona', 'persona')
            // Join with 'cuenta' to calculate total sales generated by the waiter
            .leftJoin('cuenta', 'cuenta', 'cuenta.id_pedido = pedido.id AND cuenta.D_E_L_E_T_E_D = false')
            .select("CONCAT(persona.nombre, ' ', persona.apellido)", 'mesero')
            .addSelect('usuario.id', 'usuario_id')
            .addSelect('COUNT(DISTINCT pedido.id)', 'pedidos_atendidos')
            .addSelect('COALESCE(SUM(cuenta.total), 0)', 'total_recaudado')
            .where('pedido.D_E_L_E_T_E_D = false');

        if (startDate && endDate) {
            query = query.andWhere("pedido.created_at::date >= :startDate AND pedido.created_at::date <= :endDate", { startDate, endDate });
        } else if (startDate) {
            query = query.andWhere("pedido.created_at::date >= :startDate", { startDate });
        }

        const result = await query
            .andWhere('cuenta.id_estado = 3') // Sólo contar las pagadas
            .groupBy('usuario.id')
            .addGroupBy('persona.nombre')
            .addGroupBy('persona.apellido')
            .orderBy('pedidos_atendidos', 'DESC')
            .getRawMany();

        return result.map((item) => ({
            usuario_id: item.usuario_id,
            mesero: item.mesero,
            pedidos_atendidos: parseInt(item.pedidos_atendidos, 10),
            total_recaudado: parseFloat(item.total_recaudado)
        }));
    }

    async getPedidosMeseroRendimiento(usuarioId: number, startDate?: string, endDate?: string) {
        // Query to fetch the exact orders that contributed to the waiter's performance metrics
        let query = this.pedidoRepository
            .createQueryBuilder('pedido')
            .leftJoinAndSelect('pedido.mesa', 'mesa')
            .leftJoinAndSelect('pedido.estado', 'estado')
            .leftJoin('cuenta', 'cuenta', 'cuenta.id_pedido = pedido.id AND cuenta.D_E_L_E_T_E_D = false AND cuenta.id_estado = 3')
            .addSelect('SUM(cuenta.total)', 'total_pedido')
            .where('pedido.D_E_L_E_T_E_D = false')
            .andWhere('pedido.id_usuario = :usuarioId', { usuarioId })
            // Only orders that have at least one paid account (what makes it count to performance)
            .andWhere('EXISTS (SELECT 1 FROM cuenta c WHERE c.id_pedido = pedido.id AND c."D_E_L_E_T_E_D" = false AND c.id_estado = 3)');

        if (startDate && endDate) {
            query = query.andWhere("pedido.created_at::date >= :startDate AND pedido.created_at::date <= :endDate", { startDate, endDate });
        } else if (startDate) {
            query = query.andWhere("pedido.created_at::date >= :startDate", { startDate });
        }

        const rawResults = await query
            .groupBy('pedido.id')
            .addGroupBy('mesa.id')
            .addGroupBy('estado.id')
            .addGroupBy('pedido.created_at')
            .orderBy('pedido.created_at', 'DESC')
            .getRawAndEntities();

        return rawResults.entities.map((pedido, index) => {
            const raw = rawResults.raw[index];
            return {
                id: pedido.id,
                fecha: pedido.created_at,
                mesa_numero: pedido.mesa?.numero || 'S/M',
                estado_nombre: pedido.estado?.nombre || 'Desconocido',
                total_recaudado: parseFloat(raw.total_pedido) || 0
            };
        });
    }

    async getDashboardKpis() {
        // Obtenemos la fecha local (UTC-4 para Bolivia)
        const localNow = new Date(new Date().getTime() - (4 * 60 * 60 * 1000));
        
        // Creamos límites de inicio y fin del día actual con respecto al servidor (asumiendo que guarda en UTC o similar)
        // La mejor manera de no depender de TO_CHAR que puede fallar con zonas horarias de la base de datos es pasar rangos.
        // Pero intentaremos primero simplemente construyendo las fechas de inicio y fin del día actual en "localNow" ajustado
        
        const todayStr = localNow.toISOString().split('T')[0];
        
        // Vamos a construir un start of day y end of day en UTC que correspondan al start y end of day in UTC-4
        // Example: Si en Bolivia es 00:00:00, en UTC son las 04:00:00.
        // Construimos la cadena local y la parseamos como UTC y luego le restamos el offset.
        const startOfDayUTC = new Date(`${todayStr}T00:00:00.000Z`);
        startOfDayUTC.setUTCHours(startOfDayUTC.getUTCHours() + 4); // Offset inverso para que en BD funcione (04:00Z)
        
        const endOfDayUTC = new Date(`${todayStr}T23:59:59.999Z`);
        endOfDayUTC.setUTCHours(endOfDayUTC.getUTCHours() + 4); 

        // 1. Total Sales Today (Only Completed/Paid Cuentas)
        const ventasHoy = await this.cuentaRepository
            .createQueryBuilder('cuenta')
            .select('SUM(cuenta.total)', 'total_ventas')
            .where('cuenta.D_E_L_E_T_E_D = false')
            .andWhere('cuenta.id_estado = 3') // 3 = PAGADO/COMPLETADO
            // .andWhere("TO_CHAR(cuenta.updated_at AT TIME ZONE 'UTC' AT TIME ZONE 'America/La_Paz', 'YYYY-MM-DD') = :today", { today: todayStr })
            .andWhere('cuenta.updated_at >= :startOfDay AND cuenta.updated_at <= :endOfDay', { startOfDay: startOfDayUTC, endOfDay: endOfDayUTC })
            .getRawOne();

        const total_sales_today = parseFloat(ventasHoy?.total_ventas) || 0;

        // 1b. Sales Breakdown by Payment Type (Efectivo vs QR)
        const ventasBreakdown = await this.cuentaRepository
            .createQueryBuilder('cuenta')
            .select('cuenta.tipo_pago', 'tipo_pago')
            .addSelect('SUM(cuenta.total)', 'total')
            .where('cuenta.D_E_L_E_T_E_D = false')
            .andWhere('cuenta.id_estado = 3')
            .andWhere('cuenta.updated_at >= :startOfDay AND cuenta.updated_at <= :endOfDay', { startOfDay: startOfDayUTC, endOfDay: endOfDayUTC })
            .groupBy('cuenta.tipo_pago')
            .getRawMany();
        
        let ventas_efectivo = 0;
        let ventas_qr = 0;

        ventasBreakdown.forEach(item => {
            if (item.tipo_pago === 'Efectivo') ventas_efectivo += parseFloat(item.total);
            if (item.tipo_pago === 'QR') ventas_qr += parseFloat(item.total);
        });

        // 2. Orders Processed Today
        const pedidosHoy = await this.pedidoRepository
            .createQueryBuilder('pedido')
            .select('COUNT(pedido.id)', 'total_pedidos')
            .where('pedido.D_E_L_E_T_E_D = false')
            .andWhere('pedido.created_at >= :startOfDay AND pedido.created_at <= :endOfDay', { startOfDay: startOfDayUTC, endOfDay: endOfDayUTC })
            .getRawOne();

        const orders_processed_today = parseInt(pedidosHoy?.total_pedidos, 10) || 0;

        // 3. Most Popular Item (All time or today, let's keep it simple with most popular overall or currently active)
        const popularItemResult = await this.detallePedidoRepository
            .createQueryBuilder('dp')
            .innerJoin('dp.producto', 'producto')
            .select('producto.nombre', 'nombre')
            .addSelect('SUM(dp.cantidad)', 'cantidad')
            .where('dp.D_E_L_E_T_E_D = false')
            .groupBy('producto.id')
            .addGroupBy('producto.nombre')
            .orderBy('cantidad', 'DESC')
            .limit(1)
            .getRawOne();

        const popular_item = popularItemResult ? {
            name: popularItemResult.nombre,
            orders: parseInt(popularItemResult.cantidad, 10)
        } : null;

        // 4. Recent Orders (We get the latest 5 accounts)
        const recentAccountsWithDetails = await this.cuentaRepository
            .createQueryBuilder('cuenta')
            .where('cuenta.D_E_L_E_T_E_D = false')
            .orderBy('cuenta.created_at', 'DESC')
            .take(5)
            .getMany();

        const mappedRecentOrders: any[] = [];

        for (const cuenta of recentAccountsWithDetails) {
            const detalles = await this.detallePedidoRepository
                .createQueryBuilder('dp')
                .leftJoinAndSelect('dp.producto', 'producto')
                .where('dp.cuenta = :cuentaId', { cuentaId: cuenta.id })
                .getMany();

            const items = detalles.length > 0
                ? detalles.map(d => `${d.cantidad}x ${d.producto?.nombre || 'Producto'}`).join(', ')
                : 'Sin items detallados';

            mappedRecentOrders.push({
                id: `#C${cuenta.id.toString().padStart(4, '0')}`,
                items: items,
                amount: cuenta.total,
                status: 'Completado' // Cuentas ya cerradas
            });
        }

        // Active Orders that haven't been cashed out (pending/in-prep)
        const pendingOrders = await this.pedidoRepository
            .createQueryBuilder('pedido')
            .leftJoinAndSelect('pedido.estado', 'estado')
            .where('pedido.D_E_L_E_T_E_D = false')
            .andWhere('estado.nombre IN (:...estados)', { estados: ['PENDIENTE', 'EN_PREPARACION', 'LISTO'] })
            .orderBy('pedido.created_at', 'DESC')
            .take(3)
            .getMany();

        const mappedPendingOrders: any[] = [];
        for (const pedido of pendingOrders) {
            const cuentaPendiente = await this.cuentaRepository.findOneBy({ pedido: { id: pedido.id } });
            let itemsText = 'Sin items';
            let amountVal = 0;
            if (cuentaPendiente) {
                const detalles = await this.detallePedidoRepository
                    .createQueryBuilder('dp')
                    .leftJoinAndSelect('dp.producto', 'producto')
                    .where('dp.cuenta = :cuentaId', { cuentaId: cuentaPendiente.id })
                    .getMany();
                itemsText = detalles.map(d => `${d.cantidad}x ${d.producto?.nombre}`).join(', ') || 'Sin items';
                amountVal = cuentaPendiente.total;
            }

            mappedPendingOrders.push({
                id: `#P${pedido.id.toString().padStart(4, '0')}`,
                items: itemsText,
                amount: amountVal,
                status: pedido.estado?.nombre || 'Abierto'
            });
        }

        // 5. Pedidos Eliminados Recientemente (Audit)
        const deletedOrders = await this.pedidoRepository
            .createQueryBuilder('pedido')
            .leftJoinAndSelect('pedido.estado', 'estado')
            .where('pedido.D_E_L_E_T_E_D = true')
            .orderBy('pedido.updated_at', 'DESC')
            .take(3)
            .getMany();

        const mappedDeletedOrders: any[] = [];
        for (const pedido of deletedOrders) {
            const cuenta = await this.cuentaRepository.findOneBy({ pedido: { id: pedido.id } });
            let itemsText = 'Sin items';
            let amountVal = 0;
            if (cuenta) {
                const detalles = await this.detallePedidoRepository
                    .createQueryBuilder('dp')
                    .leftJoinAndSelect('dp.producto', 'producto')
                    .where('dp.cuenta = :cuentaId', { cuentaId: cuenta.id })
                    .getMany();
                itemsText = detalles.map(d => `${d.cantidad}x ${d.producto?.nombre}`).join(', ') || 'Sin items';
                amountVal = cuenta.total;
            }

            mappedDeletedOrders.push({
                id: `#P${pedido.id.toString().padStart(4, '0')}`,
                items: `[ELIMINADO] ${itemsText}`,
                amount: amountVal,
                status: 'ELIMINADO',
                justificativo: pedido.justificativo_eliminacion
            });
        }

        // Combine recent closed accounts, pending orders, and deleted orders
        const combined_recent_activity = [...mappedDeletedOrders, ...mappedPendingOrders, ...mappedRecentOrders].slice(0, 8);

        return {
            total_sales_today,
            ventas_efectivo,
            ventas_qr,
            orders_processed_today,
            sales_growth_percentage: 0, // Placeholder for YoY or MoM growth logic
            orders_growth_percentage: 0,
            popular_item,
            recent_orders: combined_recent_activity
        };
    }

    async getPedidosEliminados() {
        const deletedOrders = await this.pedidoRepository
            .createQueryBuilder('pedido')
            .leftJoinAndSelect('pedido.usuario', 'usuario')
            .leftJoinAndSelect('usuario.persona', 'persona')
            .where('pedido.D_E_L_E_T_E_D = true')
            .orderBy('pedido.updated_at', 'DESC')
            .getMany();

        return deletedOrders.map(pedido => ({
            id: pedido.id,
            fecha: pedido.updated_at || pedido.created_at,
            responsable: pedido.usuario?.persona ? `${pedido.usuario.persona.nombre} ${pedido.usuario.persona.apellido}` : 'Usuario Desconocido',
            justificativo: pedido.justificativo_eliminacion || 'Sin justificativo registrado'
        }));
    }
}
